repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-bugbear==21.9.1',
            'flake8-comprehensions==3.6.1',
            'flake8-pytest-style==1.5.0'
        ]

-   repo: https://github.com/psf/black
    rev: 21.4b0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort
